# Window
WIDTH = 500
HEIGHT = WIDTH
MARGIN = WIDTH // 10

FPS = 60

# Board
SQUARE_SIZE = (WIDTH - 2 * MARGIN) // 3
LINE_WIDTH = SQUARE_SIZE // 15

# Symbols
SQUARE_MARGIN = SQUARE_SIZE // 6
CROSS_WIDTH = int(LINE_WIDTH * 3)
CIRCLE_WIDTH = int(CROSS_WIDTH // 1.5)
CIRLE_RADIUS = SQUARE_SIZE // 2.8

# Colors
BG_COLOR = (204, 255, 255) # Light blue
BOARD_COLOR = (0, 0, 100) # Dark blue
CIRCLE_COLOR = (0, 150, 0) # Green
CROSS_COLOR = (255, 50, 0) # Orange

# Buttons
BUTTON_WIDTH = 200
BUTTON_HEIGHT = 50

BACK_BUTTON_WIDTH = 100
BACK_BUTTON_HEIGHT = 50

# Scores
SCORE_MARGIN = MARGIN // 2
SCORE_WIDTH = 500
SCORE_HEIGHT = 50


